name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-latest
        host:
          - x64
        target:
          - x64
        node:
          - 20
        include:
          - os: macos-latest
            node: 20
            host: arm64
            target: arm64
          - os: macos-14
            node: 20
            host: arm64
            target: arm64
          - os: ubuntu-22.04-arm
            node: 20
            host: arm64
            target: arm64
          - os: ubuntu-24.04-arm
            node: 20
            host: arm64
            target: arm64
          - os: windows-11-arm
            node: 20
            host: arm64
            target: arm64
    name: ${{ matrix.os }} (host=${{ matrix.host }}, target=${{ matrix.target }})
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.host }}
      - name: Add yarn
        run: npm install -g yarn
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3
        if: contains(matrix.os, 'windows')
        with:
          msbuild-architecture: ${{ matrix.target }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Check Node compatibility
        run: node tools/semver-check.js

      - name: Add env vars
        shell: bash
        run: |
          echo "V=1" >> $GITHUB_ENV

          if [ "${{ matrix.target }}" = "x86" ]; then
            echo "TARGET=ia32" >> $GITHUB_ENV
          else
            echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
          fi

      - name: Add Linux env vars
        if: contains(matrix.os, 'ubuntu')
        run: |
          echo "CFLAGS=${CFLAGS:-} -include ../src/gcc-preinclude.h" >> $GITHUB_ENV
          echo "CXXFLAGS=${CXXFLAGS:-} -include ../src/gcc-preinclude.h" >> $GITHUB_ENV

      - name: Downgrade sqlite to 3.48 on macos
        if: contains(matrix.os, 'macos')
        run: |
          sed -i '' 's/3500000/3480000/g' deps/common-sqlite.gypi

      - name: Build binaries
        run: yarn prebuild -a ${{ env.TARGET }}

      - name: Print binary info
        if: contains(matrix.os, 'ubuntu')
        run: |
          ldd build/**/node_sqlite3.node
          echo "---"
          nm build/**/node_sqlite3.node | grep "GLIBC_" | c++filt || true
          echo "---"
          file build/**/node_sqlite3.node

      - name: Run tests
        run: yarn test

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-24.04'
        with:
          name: prebuilt-binaries
          path: prebuilds/*
          retention-days: 7

      - name: Upload binaries to GitHub Release
        run: yarn upload --upload-all ${{ github.token }}
        if: startsWith(github.ref, 'refs/tags/')

  build-qemu:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      id-token: write
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
        target:
          - linux/arm64
        variant:
          - bookworm
          - alpine3.20
        include:
          # musl x64 builds
          - target: linux/amd64
            variant: alpine3.20
            node: 20
    name: ${{ matrix.variant }} (node=${{ matrix.node }}, target=${{ matrix.target }})
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binaries and test
        run: |
          docker buildx build \
            --file ./tools/BinaryBuilder.Dockerfile \
            --load \
            --tag sqlite-builder \
            --platform ${{ matrix.target }} \
            --no-cache \
            --build-arg VARIANT=${{ matrix.variant }} \
            --build-arg NODE_VERSION=${{ matrix.node }} \
            .
          CONTAINER_ID=$(docker create -it sqlite-builder)
          docker cp $CONTAINER_ID:/usr/src/build/prebuilds/ ./prebuilds

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-24.04'
        with:
          name: prebuilt-binaries
          path: prebuilds/*
          retention-days: 14

      - name: Upload binaries to GitHub Release
        run: yarn install --ignore-scripts && yarn upload --upload-all ${{ github.token }}
        if: startsWith(github.ref, 'refs/tags/')
